= Overview
:page-layout: home
:!sectids:

= Overview
:page-layout: home
:!sectids:

For years the way to go to get something installed in an organization was finding the person of reference and file a request: by email, by phone, via a procurement portal, you name it.

Of course this person had the knowledge and the means (inn general) to fulfill your request and get you what you wanted/needed. Sometimes we call this kind of person `operator` or `the one who knows`, but let's stick to the 1st more down-to-earth name.

Well, in the kubernetes world an operator is the same, true, it's an entity not a person, but it has the knowledge and (hopefully) the resources to get you what you want. The knowledge will be (no wonder) in the shape of code running in a POD and resources, well, kubernetes is all about managing and orchestrating resources, isn't it?

But you maybe wondering... code in a POD, that like saying nothing. True, this code is special it has to follow the link:https://kubernetes.io/docs/concepts/architecture/controller/#controller-pattern[controller pattern, window=_blank].

[#controllers]
== Controllers

[quote]
____
A controller tracks at least one Kubernetes resource type. These objects have a spec field that represents the desired state. The controller(s) for that resource are responsible for making the current state come closer to that desired state.
____

So, imagine you want and operator capable of deploying a Kafka cluster, you would need:

* a custom resource that has a spec section declaring the desired state
* a controller watching this kind of resource and reacting to events like: creation, update, deletion, ...

This custom resource should have a spec section declaring, for instance that you want 3 zoo-keeper instances and 3 cluster nodes with ephemeral storage. Find below a sample `Kafka` custom resource.

NOTE: Custom resources in kubernetes have a formal definition link:https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/[*Custom Resource Definition*, window=_blank] which is in fact the way to extend the kubernetes native set of objects.

.Sample Kafka Custom Resource
[.console-output]
[source,yaml,options="nowrap",subs="attributes+"]
----
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    ...
    version: 2.6.0
    storage:
      type: ephemeral
    replicas: 3
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3
----

Ok, you have a way to specifiy the desired state, now you need some code that is triggered everytime something happens to `Kafka` resources. So, all you have to do is building a controller watching this type of objects!

Wait... this is not an easy task... which language would you use... which client library to import... samples?

No worries, the link:https://operatorframework.io/[Operator Framework, window=_blank] got you covered and offers several SDKs (Go, Ansible and Helm) to build operators in a much easier way. Not only that, this project also provides with a centrl piece in charge of the lifecycle of operators, the link:https://github.com/operator-framework/operator-lifecycle-manager[Operator Lifecycle Manager, window=_blank].

[NOTE]
==========
This tutorial will guide you through the process of building and evolving an operator using your favourite automation language, Ansible, using the link:https://sdk.operatorframework.io/[Operator SDK, window=_blank].
==========

[#tldr]
== TL;DR

You are going to *build version 0.0.1 of an operator that deploys a Memcached cluster* with a dynamic size, this includes learning how to build the image, the bundle and the bundle index. TODO xref here!!!

Then we will show you how to *install the link:https://github.com/operator-framework/operator-lifecycle-manager[Operator Lifecycle Manager, window=_blank] and how to configure it to be able to install your very own operator*. 

Finally you will *evolve your operator to version 0.0.2 and see how the installed operator upgrades itself* seamlessly.

[#details]
== Details

The next steps are basically the ones in link:https://sdk.operatorframework.io/docs/building-operators/ansible/tutorial/[this]
guide. I just compiled the steps in that guide and simplified some things. I hope ;-)

### Lab Parameters

This lab supports both link:site.yml#L17[Antora variables] and query parameters. Query params makes the workshop content dynamic, like URLs specific for your cluster to copy and paste.

NOTE: In the table above, CRC and Playground links use them.

Here's the list of all query params used (they are all optional, but generated links won't work unless at least `CLUSTER_SUBDOMAIN` is set):

[%header,cols=2*] 
|===
|PARAM
|Description

|`CLUSTER_SUBDOMAIN`
|The subdomain for your OpenShift cluster in the form `apps.<cluster_name>.<base_domain>`, e.g. `apps.openshift.mydomain.tld`

|`USERNAME`
| The username of your OpenShift cluster

|`PASSWORD`
| The password for your OpenShift cluster

|===

Example:

https://atarazana.github.io/ansible-operator-road-trip-guide/ansible-operator-road-trip-guide/main/index.html?CLUSTER_SUBDOMAIN=apps-crc.testing&USERNAME=developer&PASSWORD=developer

## Contributing

Please refer to the link:CONTRIBUTING.adoc#contributing-guide[how to contribute] on how you can contribute to the tutorial