runtime:
  cache_dir: ./.cache/antora

site:
  title: Ansible Operator Road Trip Guide
  url: https://atarazana.github.io/ansible-operator-road-trip-guide
  start_page: ansible-operator-road-trip-guide::index.adoc

content:
  sources:
    - url: git@github.com:atarazana/ansible-operator-road-trip-guide.git
      tags: []
      branches: [master]
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
    #title: Ansible Operator Road Trip Guide
    git_base: https://github.com/atarazana 
    git_uri: ansible-operator-road-trip-guide
    git_ref: master
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-scholars/course-ui/releases/download/v0.1.8/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
